Azure Build

diff --git a/.github/workflows/build_azure.yml b/.github/workflows/build_azure.yml
--- a/.github/workflows/build_azure.yml
+++ b/.github/workflows/build_azure.yml
@@ -24,12 +24,18 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-      - name: Install AZ
-        uses: ./.github/actions/install_az
+      - name: 'Az CLI login'
+        uses: azure/login@v1
         with:
-          acr_password: ${{secrets.AZURE_SP_KEY}}
-          mq_acr_user: ${{secrets.AZURE_SP_USERNAME}}
-          mq_aks_tenant_id: ${{secrets.AZURE_TENANT}}
+            client-id: ${{ secrets.ARM_CLIENT_ID }}
+            tenant-id: ${{ secrets.ARM_TENANT_ID }}
+            subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+    
+      - name: 'Run Azure CLI commands'
+        run: |
+            az account show
+            az group list
+            pwd 
       - name: install terraform
         run: |
           wget -O- https://apt.releases.hashicorp.com/gpg | \
@@ -42,34 +48,34 @@ jobs:
           sudo apt-get -y install terraform
       - name: Install kubectl
         run: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl
-      - name: Azure Up
-        run: ./azure-up.sh
-        working-directory: azure-infra
-      - name: sleep
-        run: sleep 60
-      - name: Check ArgoCD
-        run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=argocd-server --namespace argocd --timeout=5s
-      - name: Check Ingress
-        run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=controller --namespace ingress --timeout=5s
-      # - name: Check Metric API Service
-      #   run: |
-      #     max_retry=10
-      #     counter=0
-      #     until if [[ `kubectl get apiservice -l k8s-app=metrics-server --output=jsonpath={.items..status.conditions..status}` == "True" ]]; then exit 1; fi
-      #     do
-      #       sleep 60
-      #       [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
-      #       echo "Trying again. Try #$counter"
-      #       ((counter++))
-      #     done
-      - name: Check Keda
-        run: kubectl wait --for=condition=ready pod -l app=keda-operator --namespace keda
-      - name: Check Prometheus
-        run: kubectl wait --for=condition=ready pod -l app=kube-prometheus-stack-operator --namespace monitoring
-      - name: Check Cert Manager
-        run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=cert-manager --namespace cert-manager
-      - name: Azure Down
-        if: always()
-        run: ./azure-down.sh
-        working-directory: azure-infra
+      # - name: Azure Up
+      #   run: ./azure-up.sh
+      #   working-directory: azure-infra
+      # - name: sleep
+      #   run: sleep 60
+      # - name: Check ArgoCD
+      #   run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=argocd-server --namespace argocd --timeout=5s
+      # - name: Check Ingress
+      #   run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=controller --namespace ingress --timeout=5s
+      # # - name: Check Metric API Service
+      # #   run: |
+      # #     max_retry=10
+      # #     counter=0
+      # #     until if [[ `kubectl get apiservice -l k8s-app=metrics-server --output=jsonpath={.items..status.conditions..status}` == "True" ]]; then exit 1; fi
+      # #     do
+      # #       sleep 60
+      # #       [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
+      # #       echo "Trying again. Try #$counter"
+      # #       ((counter++))
+      # #     done
+      # - name: Check Keda
+      #   run: kubectl wait --for=condition=ready pod -l app=keda-operator --namespace keda
+      # - name: Check Prometheus
+      #   run: kubectl wait --for=condition=ready pod -l app=kube-prometheus-stack-operator --namespace monitoring
+      # - name: Check Cert Manager
+      #   run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=cert-manager --namespace cert-manager
+      # - name: Azure Down
+      #   if: always()
+      #   run: ./azure-down.sh
+      #   working-directory: azure-infra
 
